default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-yaml
      - id: check-ast
      - id: check-json
      - id: check-toml

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.3
    hooks:
      - id: check-github-workflows
        args: [ "--verbose" ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        args: [ "--lock" ]
      - id: poetry-lock
        args: [ "--no-update" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [ "--fix", "--show-fixes" ]
      - id: ruff-format
